### ISSUE TITLE
commentit.js seems down

### ISSUE THREAD

**Issue by tvvocold** [guilro/commentit#11]
Hi,
 https://commentit.io/static/embed/dist/commentit.js seems down, maybe you could use 
 CDN ( like https://rawgit.com or https://cloudflare.com ) to server the static file?

<img width="1265" alt="2017-08-12 12 12 19" src="https://user-images.githubusercontent.com/4530539/29222044-73203568-7ef3-11e7-9caa-58ed908e2411.png">

**Comment by guilro** [comment]
Sorry, the server was down and I was off for a few days.

I am not sure using a CDN would change the situation a lot, since just the client JS is not enough to make commentit.io work. The server application must be up and running too.

**Comment by tvvocold** [comment]
Thank you very much!
