### ISSUE TITLE
Small grammatical error - comment submission

### ISSUE THREAD

**Issue by kylegraycar** [guilro/commentit#2]
Thanks for putting this together! I'm very new to Jekyll and Gihub, but I noticed a very small grammatical error for the message displayed after someone submits their comments.

The message currently reads:
"Your comment has been submitted. It will appear when the site owner approve it."

I recommended adding an "s" to "approve." So it should read:
"Your comment has been submitted. It will appear when the site owner approves it."

This could be my own preference, but I also suggest changing "when" with "once." Maybe also add a "thank you?" So:
"Thank you! Your comment has been submitted. It will appear once the site owner approves it."

Hope this is helpful!

**Comment by guilro** [comment]
Thanks for your suggestion and for testing commentit ;). It should be online now !
