### ISSUE TITLE
Can this support hexo?

### ISSUE THREAD

**Issue by S-X-ShaX** [guilro/commentit#5]
Hexo is another static html render,just like jekyll but powered by Node.js.I think commentit is good and want it support other tools,not only jekyll,could you do this?

**Comment by guilro** [comment]
Hello. Commentit is more tied to GitHub than it is to Jekyll : it is using the GitHub API to push new comments to the GitHub repo where the Jekyll website is hosted. As using another static HTML render imply hosting it on another host, this is where lies the difficulty. You could try to implement another API to push your comments to this other host, but I will not take the time myself to do it, I am concentrating on other projects ;)

**Comment by yanhaijing** [comment]
yes support
