### ISSUE TITLE
Comment Fail

### ISSUE THREAD

**Issue by dbarobin** [guilro/commentit#8]
When I sigh-in with GitHub and comment article, error trigger.

<img width="492" alt="screen shot 2017-02-02 at 17 10 52" src="https://cloud.githubusercontent.com/assets/3949252/22543329/0c95d578-e96b-11e6-8d9b-ba87d69dff02.png">

The URL of browser:

> http://localhost:3000/auth/github/callback?code=1b7a7f02fd729022b31d

Thanks!

**Comment by guilro** [comment]
Thanks, fixed !
