### ISSUE TITLE
Error: could not commit the comment to github (repository or file not found)

### ISSUE THREAD

**Issue by yanhaijing** [guilro/commentit#9]
![20170405160132](https://cloud.githubusercontent.com/assets/3192087/24695666/36effd38-1a19-11e7-87f9-e0c0658d8c75.png)
![20170405160153](https://cloud.githubusercontent.com/assets/3192087/24695668/37020ed8-1a19-11e7-8142-7393fa898fb2.png)

**Comment by yanhaijing** [comment]
why

**Comment by yanhaijing** [comment]
???????????????

**Comment by yanhaijing** [comment]
?????????

**Comment by mnhkahn** [comment]
the same problem.

**Comment by LKI** [comment]
Please check your settings at [commentit/settings](https://commentit.io/settings)

Currently there is some bugs for `Create branch and pull requests for comments`.

You can use `Commit directly to master or gh-pages branch` and it should fix the problem

**Comment by yanhaijing** [comment]
@LKI 
the method(way) not success, still problem

**Comment by yanhaijing** [comment]
my reps name is yanhaijing.github.com;not is yanhaijing.github.io.
Do not know if there is no impact

**Comment by guilro** [comment]
Hello all ! I am deeply sorry, but I am very busy until the end of the month, and may not able to fix it before. I will do my best to fix it in two or three weeks.

**Comment by LKI** [comment]
@yanhaijing You can try to rename to github.io

I remember mine was github.com and I did rename it

**Comment by yanhaijing** [comment]
@LKI thansk! but i worry about rename reps name impact service

**Comment by yanhaijing** [comment]
@guilro common on!!! to many people waiting your great work!!!

**Comment by yanhaijing** [comment]
i try rename is success, this is reason

**Comment by saixia** [comment]
![image](https://user-images.githubusercontent.com/12034029/27275718-4c444054-550b-11e7-847e-df9bd96ae0e8.png)
I rename my reps name, but I still get the same error(Error: could not commit the comment to github (repository or file not found)). @LKI @yanhaijing

**Comment by wendyltan** [comment]
Me too,I found that i can't comment on my own blog

**Comment by guilro** [comment]
Commentit.io is currently up at the moment :)

**Comment by guilro** [comment]
I am closing this issue since the problem there was when it was created is solved. Please open another issue if there is a new bug :)

**Comment by liminany** [comment]
@guilro I also have same problem.
post data:
{"username":"liminany","content":"666","csrf":"8ebcecad-3937-4a7d-8f3f-de6316a5159f","path":"index.html"}

url:https://commentit.io/comment/liminany/m

my Rep: https://github.com/liminany/m 
https://liminany.github.io/m

**Comment by guilro** [comment]
@liminany you don't have YAML front-matter in `index.html`. You need to have one so it can be updated.
